/*

This file gathers the relevant ICD codes for comorbidities found in the 
epilepsy-specific comorbidity index (ESCI).

TODO: VARCHAR(10) is throwing an error for unknown columns even though those won't exist after the join
- currently a WHERE clause is added, though it likely adds inefficiency

*/


DROP TABLE IF EXISTS #ICD9EsCriteria;
SELECT
    *
INTO
    #ICD9EsCriteria
FROM (VALUES
    ('415.0%', 'Pulmonary circulation disorders'),
    ('415.1%', 'Pulmonary circulation disorders'),
    ('416%', 'Pulmonary circulation disorders'),
    ('417.0%', 'Pulmonary circulation disorders'),
    ('417.8%', 'Pulmonary circulation disorders'),
    ('419.9%', 'Pulmonary circulation disorders'),

    ('401%', 'Hypertension'),
    ('402%', 'Hypertension'),
    ('403%', 'Hypertension'),
    ('404%', 'Hypertension'),
    ('405%', 'Hypertension'),

    ('426.0%', 'Cardiac arrhythmias'),
    ('426.13%', 'Cardiac arrhythmias'),
    ('426.7%', 'Cardiac arrhythmias'),
    ('426.9%', 'Cardiac arrhythmias'),
    ('426.10%', 'Cardiac arrhythmias'),
    ('426.12%', 'Cardiac arrhythmias'),
    ('427.0%', 'Cardiac arrhythmias'),
    ('427.1%', 'Cardiac arrhythmias'),
    ('427.2%', 'Cardiac arrhythmias'),
    ('427.3%', 'Cardiac arrhythmias'),
    ('427.4%', 'Cardiac arrhythmias'),
    ('427.6%', 'Cardiac arrhythmias'),
    ('427.8%', 'Cardiac arrhythmias'),
    ('427.9%', 'Cardiac arrhythmias'),
    ('785.0%', 'Cardiac arrhythmias'),
    ('996.01%', 'Cardiac arrhythmias'),
    ('996.04%', 'Cardiac arrhythmias'),
    ('V45.0%', 'Cardiac arrhythmias'),
    ('V53.3%', 'Cardiac arrhythmias'),

    ('398.91%', 'Congestive heart failure'),
    ('402.01%', 'Congestive heart failure'),
    ('402.11%', 'Congestive heart failure'),
    ('402.91%', 'Congestive heart failure'),
    ('404.01%', 'Congestive heart failure'),
    ('404.03%', 'Congestive heart failure'),
    ('404.11%', 'Congestive heart failure'),
    ('404.13%', 'Congestive heart failure'),
    ('404.91%', 'Congestive heart failure'),
    ('404.93%', 'Congestive heart failure'),
    ('425.4%', 'Congestive heart failure'),
    ('425.5%', 'Congestive heart failure'),
    ('425.7%', 'Congestive heart failure'),
    ('425.8%', 'Congestive heart failure'),
    ('425.9%', 'Congestive heart failure'),
    ('428%', 'Congestive heart failure'),

    ('093.0%', 'Peripheral vascular disease'),
    ('437.3%', 'Peripheral vascular disease'),
    ('440%', 'Peripheral vascular disease'),
    ('441%', 'Peripheral vascular disease'),
    ('443.1%', 'Peripheral vascular disease'),
    ('443.2%', 'Peripheral vascular disease'),
    ('443.8%', 'Peripheral vascular disease'),
    ('443.9%', 'Peripheral vascular disease'),
    ('447.1%', 'Peripheral vascular disease'),
    ('557.1%', 'Peripheral vascular disease'),
    ('557.9%', 'Peripheral vascular disease'),
    ('V43.4%', 'Peripheral vascular disease'),

    ('403.01%', 'Renal disease'),
    ('403.11%', 'Renal disease'),
    ('403.91%', 'Renal disease'),
    ('404.02%', 'Renal disease'),
    ('404.03%', 'Renal disease'),
    ('404.12%', 'Renal disease'),
    ('404.13%', 'Renal disease'),
    ('404.92%', 'Renal disease'),
    ('404.93%', 'Renal disease'),
    ('582%', 'Renal disease'),
    ('583.0%', 'Renal disease'),
    ('583.1%', 'Renal disease'),
    ('583.2%', 'Renal disease'),
    ('583.4%', 'Renal disease'),
    ('583.6%', 'Renal disease'),
    ('583.7%', 'Renal disease'),
    ('585%', 'Renal disease'),
    ('586%', 'Renal disease'),
    ('588.0%', 'Renal disease'),
    ('V42.0%', 'Renal disease'),
    ('V45.1%', 'Renal disease'),
    ('V56%', 'Renal disease'),

    ('140%', 'Solid tumor without metastases'),
    ('141%', 'Solid tumor without metastases'),
    ('142%', 'Solid tumor without metastases'),
    ('143%', 'Solid tumor without metastases'),
    ('144%', 'Solid tumor without metastases'),
    ('145%', 'Solid tumor without metastases'),
    ('146%', 'Solid tumor without metastases'),
    ('147%', 'Solid tumor without metastases'),
    ('148%', 'Solid tumor without metastases'),
    ('149%', 'Solid tumor without metastases'),
    ('150%', 'Solid tumor without metastases'),
    ('151%', 'Solid tumor without metastases'),
    ('152%', 'Solid tumor without metastases'),
    ('153%', 'Solid tumor without metastases'),
    ('154%', 'Solid tumor without metastases'),
    ('155%', 'Solid tumor without metastases'),
    ('156%', 'Solid tumor without metastases'),
    ('157%', 'Solid tumor without metastases'),
    ('158%', 'Solid tumor without metastases'),
    ('159%', 'Solid tumor without metastases'),
    ('160%', 'Solid tumor without metastases'),
    ('161%', 'Solid tumor without metastases'),
    ('162%', 'Solid tumor without metastases'),
    ('163%', 'Solid tumor without metastases'),
    ('164%', 'Solid tumor without metastases'),
    ('165%', 'Solid tumor without metastases'),
    ('166%', 'Solid tumor without metastases'),
    ('167%', 'Solid tumor without metastases'),
    ('168%', 'Solid tumor without metastases'),
    ('169%', 'Solid tumor without metastases'),
    ('170%', 'Solid tumor without metastases'),
    ('171%', 'Solid tumor without metastases'),
    ('172%', 'Solid tumor without metastases'),
    ('174%', 'Solid tumor without metastases'),
    ('175%', 'Solid tumor without metastases'),
    ('176%', 'Solid tumor without metastases'),
    ('177%', 'Solid tumor without metastases'),
    ('178%', 'Solid tumor without metastases'),
    ('179%', 'Solid tumor without metastases'),
    ('180%', 'Solid tumor without metastases'),
    ('181%', 'Solid tumor without metastases'),
    ('182%', 'Solid tumor without metastases'),
    ('183%', 'Solid tumor without metastases'),
    ('184%', 'Solid tumor without metastases'),
    ('185%', 'Solid tumor without metastases'),
    ('186%', 'Solid tumor without metastases'),
    ('187%', 'Solid tumor without metastases'),
    ('188%', 'Solid tumor without metastases'),
    ('189%', 'Solid tumor without metastases'),
    ('190%', 'Solid tumor without metastases'),
    ('193%', 'Solid tumor without metastases'),
    ('194.0%', 'Solid tumor without metastases'),
    ('194.1%', 'Solid tumor without metastases'),
    ('194.5%', 'Solid tumor without metastases'),
    ('194.6%', 'Solid tumor without metastases'),
    ('194.8%', 'Solid tumor without metastases'),
    ('194.9%', 'Solid tumor without metastases'),
    ('195%', 'Solid tumor without metastases'),

    ('334.1%', 'Paraplegia and hemiplegia'),
    ('342.0%', 'Paraplegia and hemiplegia'),
    ('342.1%', 'Paraplegia and hemiplegia'),
    ('342.8%', 'Paraplegia and hemiplegia'),
    ('342.9%', 'Paraplegia and hemiplegia'),
    ('344.0%', 'Paraplegia and hemiplegia'),
    ('344.1%', 'Paraplegia and hemiplegia'),
    ('344.2%', 'Paraplegia and hemiplegia'),
    ('344.3%', 'Paraplegia and hemiplegia'),
    ('344.4%', 'Paraplegia and hemiplegia'),
    ('344.5%', 'Paraplegia and hemiplegia'),
    ('344.6%', 'Paraplegia and hemiplegia'),
    ('344.9%', 'Paraplegia and hemiplegia'),

    ('507.0%', 'Aspiration pneumonia'),

    ('290%', 'Dementia'),
    ('294.1%', 'Dementia'),
    ('331.2%', 'Dementia'),

    ('191%', 'Brain tumor'),
    ('192%', 'Brain tumor'),
    ('194.3%', 'Brain tumor'),
    ('194.4%', 'Brain tumor'),
    ('200.5%', 'Brain tumor'),
    ('225.0%', 'Brain tumor'),
    ('225.1%', 'Brain tumor'),
    ('225.2%', 'Brain tumor'),
    ('225.8%', 'Brain tumor'),
    ('225.9%', 'Brain tumor'),
    ('227.3%', 'Brain tumor'),
    ('227.4%', 'Brain tumor'),
    ('237.0%', 'Brain tumor'),
    ('237.1%', 'Brain tumor'),
    ('237.5%', 'Brain tumor'),
    ('237.6%', 'Brain tumor'),
    ('237.7%', 'Brain tumor'),
    ('237.9%', 'Brain tumor'),
    ('239.6%', 'Brain tumor'),

    ('348.1%', 'Anoxic brain injury'),
    ('768.5%', 'Anoxic brain injury'),
    ('768.6%', 'Anoxic brain injury'),
    ('768.7%', 'Anoxic brain injury'),
    ('768.9%', 'Anoxic brain injury'),

    ('456.0%', 'Moderate or severe liver disease'),
    ('456.1%', 'Moderate or severe liver disease'),
    ('456.2%', 'Moderate or severe liver disease'),
    ('572.2%', 'Moderate or severe liver disease'),
    ('572.3%', 'Moderate or severe liver disease'),
    ('572.4%', 'Moderate or severe liver disease'),
    ('572.8%', 'Moderate or severe liver disease'),

    ('196%', 'Metastatic cancer'),
    ('197%', 'Metastatic cancer'),
    ('198%', 'Metastatic cancer'),
    ('199%', 'Metastatic cancer')
) AS criteria (ICD9Prefix, Comorbidity)
;

DROP TABLE IF EXISTS #ICD10EsCriteria;
SELECT
    *
INTO
    #ICD10EsCriteria
FROM (VALUES
    ('I26%', 'Pulmonary circulation disorders'),
    ('I27%', 'Pulmonary circulation disorders'),
    ('I28.0%', 'Pulmonary circulation disorders'),
    ('I28.8%', 'Pulmonary circulation disorders'),
    ('I28.9%', 'Pulmonary circulation disorders'),

    ('I10%', 'Hypertension'),
    ('I11%', 'Hypertension'),
    ('I12%', 'Hypertension'),
    ('I13%', 'Hypertension'),
    ('I15%', 'Hypertension'),

    ('I44.1%', 'Cardiac arrhythmias'),
    ('I44.2%', 'Cardiac arrhythmias'),
    ('I44.3%', 'Cardiac arrhythmias'),
    ('I45.6%', 'Cardiac arrhythmias'),
    ('I45.9%', 'Cardiac arrhythmias'),
    ('I47%', 'Cardiac arrhythmias'),
    ('I48%', 'Cardiac arrhythmias'),
    ('I49%', 'Cardiac arrhythmias'),
    ('R00.0%', 'Cardiac arrhythmias'),
    ('R00.1%', 'Cardiac arrhythmias'),
    ('R00.8%', 'Cardiac arrhythmias'),
    ('T82.1%', 'Cardiac arrhythmias'),
    ('Z45.0%', 'Cardiac arrhythmias'),
    ('Z95.0%', 'Cardiac arrhythmias'),

    ('I09.9%', 'Congestive heart failure'),
    ('I11.0%', 'Congestive heart failure'),
    ('I13.0%', 'Congestive heart failure'),
    ('I13.2%', 'Congestive heart failure'),
    ('I25.5%', 'Congestive heart failure'),
    ('I42.0%', 'Congestive heart failure'),
    ('I42.5%', 'Congestive heart failure'),
    ('I42.6%', 'Congestive heart failure'),
    ('I42.7%', 'Congestive heart failure'),
    ('I42.8%', 'Congestive heart failure'),
    ('I42.9%', 'Congestive heart failure'),
    ('I43%', 'Congestive heart failure'),
    ('I50%', 'Congestive heart failure'),
    ('P29.0%', 'Congestive heart failure'),

    ('I70%', 'Peripheral vascular disease'),
    ('I71%', 'Peripheral vascular disease'),
    ('I73.1%', 'Peripheral vascular disease'),
    ('I73.8%', 'Peripheral vascular disease'),
    ('I73.9%', 'Peripheral vascular disease'),
    ('I77.1%', 'Peripheral vascular disease'),
    ('I79.0%', 'Peripheral vascular disease'),
    ('I79.2%', 'Peripheral vascular disease'),
    ('K55.1%', 'Peripheral vascular disease'),
    ('K55.8%', 'Peripheral vascular disease'),
    ('K55.9%', 'Peripheral vascular disease'),
    ('Z95.8%', 'Peripheral vascular disease'),
    ('Z95.9%', 'Peripheral vascular disease'),

    ('I12.0%', 'Renal disease'),
    ('I13.1%', 'Renal disease'),
    ('N03.2%', 'Renal disease'),
    ('N03.3%', 'Renal disease'),
    ('N03.4%', 'Renal disease'),
    ('N03.5%', 'Renal disease'),
    ('N03.6%', 'Renal disease'),
    ('N03.7%', 'Renal disease'),
    ('N05.2%', 'Renal disease'),
    ('N05.3%', 'Renal disease'),
    ('N05.4%', 'Renal disease'),
    ('N05.5%', 'Renal disease'),
    ('N05.6%', 'Renal disease'),
    ('N05.7%', 'Renal disease'),
    ('N18%', 'Renal disease'),
    ('N19%', 'Renal disease'),
    ('N25.0%', 'Renal disease'),
    ('Z49.0%', 'Renal disease'),
    ('Z49.1%', 'Renal disease'),
    ('Z49.2%', 'Renal disease'),
    ('Z94.0%', 'Renal disease'),
    ('Z99.2%', 'Renal disease'),

    ('C00%', 'Solid tumor without metastases'),
    ('C01%', 'Solid tumor without metastases'),
    ('C02%', 'Solid tumor without metastases'),
    ('C03%', 'Solid tumor without metastases'),
    ('C04%', 'Solid tumor without metastases'),
    ('C05%', 'Solid tumor without metastases'),
    ('C06%', 'Solid tumor without metastases'),
    ('C07%', 'Solid tumor without metastases'),
    ('C08%', 'Solid tumor without metastases'),
    ('C09%', 'Solid tumor without metastases'),
    ('C10%', 'Solid tumor without metastases'),
    ('C11%', 'Solid tumor without metastases'),
    ('C12%', 'Solid tumor without metastases'),
    ('C13%', 'Solid tumor without metastases'),
    ('C14%', 'Solid tumor without metastases'),
    ('C15%', 'Solid tumor without metastases'),
    ('C16%', 'Solid tumor without metastases'),
    ('C17%', 'Solid tumor without metastases'),
    ('C18%', 'Solid tumor without metastases'),
    ('C19%', 'Solid tumor without metastases'),
    ('C20%', 'Solid tumor without metastases'),
    ('C21%', 'Solid tumor without metastases'),
    ('C22%', 'Solid tumor without metastases'),
    ('C23%', 'Solid tumor without metastases'),
    ('C24%', 'Solid tumor without metastases'),
    ('C25%', 'Solid tumor without metastases'),
    ('C26%', 'Solid tumor without metastases'),
    ('C30%', 'Solid tumor without metastases'),
    ('C31%', 'Solid tumor without metastases'),
    ('C32%', 'Solid tumor without metastases'),
    ('C33%', 'Solid tumor without metastases'),
    ('C34%', 'Solid tumor without metastases'),
    ('C37%', 'Solid tumor without metastases'),
    ('C38%', 'Solid tumor without metastases'),
    ('C39%', 'Solid tumor without metastases'),
    ('C40%', 'Solid tumor without metastases'),
    ('C41%', 'Solid tumor without metastases'),
    ('C43%', 'Solid tumor without metastases'),
    ('C45%', 'Solid tumor without metastases'),
    ('C46%', 'Solid tumor without metastases'),
    ('C47%', 'Solid tumor without metastases'),
    ('C48%', 'Solid tumor without metastases'),
    ('C49%', 'Solid tumor without metastases'),
    ('C50%', 'Solid tumor without metastases'),
    ('C51%', 'Solid tumor without metastases'),
    ('C52%', 'Solid tumor without metastases'),
    ('C53%', 'Solid tumor without metastases'),
    ('C54%', 'Solid tumor without metastases'),
    ('C55%', 'Solid tumor without metastases'),
    ('C56%', 'Solid tumor without metastases'),
    ('C57%', 'Solid tumor without metastases'),
    ('C58%', 'Solid tumor without metastases'),
    ('C60%', 'Solid tumor without metastases'),
    ('C61%', 'Solid tumor without metastases'),
    ('C62%', 'Solid tumor without metastases'),
    ('C63%', 'Solid tumor without metastases'),
    ('C64%', 'Solid tumor without metastases'),
    ('C65%', 'Solid tumor without metastases'),
    ('C66%', 'Solid tumor without metastases'),
    ('C67%', 'Solid tumor without metastases'),
    ('C68%', 'Solid tumor without metastases'),
    ('C69%', 'Solid tumor without metastases'),
    ('C73%', 'Solid tumor without metastases'),
    ('C74%', 'Solid tumor without metastases'),
    ('C75.0%', 'Solid tumor without metastases'),
    ('C75.4%', 'Solid tumor without metastases'),
    ('C75.5%', 'Solid tumor without metastases'),
    ('C75.8%', 'Solid tumor without metastases'),
    ('C75.9%', 'Solid tumor without metastases'),
    ('C76%', 'Solid tumor without metastases'),
    ('C97%', 'Solid tumor without metastases'),

    ('G81.0%', 'Paraplegia and hemiplegia'),
    ('G81.1%', 'Paraplegia and hemiplegia'),
    ('G81.9%', 'Paraplegia and hemiplegia'),
    ('G82.0%', 'Paraplegia and hemiplegia'),
    ('G04.1%', 'Paraplegia and hemiplegia'),
    ('G11.4%', 'Paraplegia and hemiplegia'),
    ('G83.0%', 'Paraplegia and hemiplegia'),
    ('G83.1%', 'Paraplegia and hemiplegia'),
    ('G83.2%', 'Paraplegia and hemiplegia'),
    ('G83.3%', 'Paraplegia and hemiplegia'),
    ('G83.4%', 'Paraplegia and hemiplegia'),
    ('G83.9%', 'Paraplegia and hemiplegia'),

    ('J69.0%', 'Aspiration pneumonia'),

    ('F00%', 'Dementia'),
    ('F01%', 'Dementia'),
    ('F02%', 'Dementia'),
    ('F03%', 'Dementia'),
    ('F05.1%', 'Dementia'),
    ('G30%', 'Dementia'),
    ('G31.1%', 'Dementia'),

    ('C70%', 'Brain tumor'),
    ('C71%', 'Brain tumor'),
    ('C72%', 'Brain tumor'),
    ('C75.1%', 'Brain tumor'),
    ('C75.2%', 'Brain tumor'),
    ('C75.3%', 'Brain tumor'),
    ('D33.0%', 'Brain tumor'),
    ('D33.1%', 'Brain tumor'),
    ('D33.2%', 'Brain tumor'),
    ('D33.7%', 'Brain tumor'),
    ('D33.9%', 'Brain tumor'),
    ('D35.2%', 'Brain tumor'),
    ('D35.3%', 'Brain tumor'),
    ('D35.4%', 'Brain tumor'),
    ('D42.0%', 'Brain tumor'),
    ('D42.9%', 'Brain tumor'),
    ('D43.0%', 'Brain tumor'),
    ('D43.1%', 'Brain tumor'),
    ('D43.2%', 'Brain tumor'),
    ('D43.3%', 'Brain tumor'),
    ('D43.7%', 'Brain tumor'),
    ('D43.9%', 'Brain tumor'),
    ('D44.3%', 'Brain tumor'),
    ('D44.4%', 'Brain tumor'),
    ('D44.5%', 'Brain tumor'),

    ('G93.1%', 'Anoxic brain injury'),
    ('P21%', 'Anoxic brain injury'),
    ('P91.6%', 'Anoxic brain injury'),

    ('I85.0%', 'Moderate or severe liver disease'),
    ('I85.9%', 'Moderate or severe liver disease'),
    ('I86.4%', 'Moderate or severe liver disease'),
    ('I98.2%', 'Moderate or severe liver disease'),
    ('K70.4%', 'Moderate or severe liver disease'),
    ('K71.1%', 'Moderate or severe liver disease'),
    ('K72.1%', 'Moderate or severe liver disease'),
    ('K72.9%', 'Moderate or severe liver disease'),
    ('K76.5%', 'Moderate or severe liver disease'),
    ('K76.6%', 'Moderate or severe liver disease'),
    ('K76.7%', 'Moderate or severe liver disease'),

    ('C77%', 'Metastatic cancer'),
    ('C78%', 'Metastatic cancer'),
    ('C79%', 'Metastatic cancer'),
    ('C80%', 'Metastatic cancer')
) AS criteria (ICD10Prefix, Comorbidity)
;

DROP TABLE IF EXISTS ORD_Haneef_202402056D.Dflt.rnEsICD9;
CREATE TABLE ORD_Haneef_202402056D.Dflt.rnEsICD9 (
    ICD9SID INT PRIMARY KEY,
    ICD9Code VARCHAR(10),
    PulmCirc BIT,
    HTN BIT,
    Arrhy BIT,
    CHF BIT,
    Vasc BIT,
    Renal BIT,
    Tumor BIT,
    Plegia BIT,
    Aspir BIT,
    Demen BIT,
    BrainTumor BIT,
    AnoxicBrain BIT,
    ModSevLiver BIT,
    MetCancer BIT
);
INSERT INTO ORD_Haneef_202402056D.Dflt.rnEsICD9 (
    ICD9SID,
    ICD9Code, 
    PulmCirc,
    HTN,
    Arrhy,
    CHF,
    Vasc,
    Renal,
    Tumor,
    Plegia,
    Aspir,
    Demen,
    BrainTumor,
    AnoxicBrain,
    ModSevLiver,
    MetCancer
)
SELECT
    icd.ICD9SID,
    icd.ICD9Code,
    MAX(CASE WHEN crit.Comorbidity = 'Pulmonary circulation disorders' THEN 1 ELSE 0 END) AS PulmCirc,
    MAX(CASE WHEN crit.Comorbidity = 'Hypertension' THEN 1 ELSE 0 END) AS HTN,
    MAX(CASE WHEN crit.Comorbidity = 'Cardiac arrhythmias' THEN 1 ELSE 0 END) AS Arrhy,
    MAX(CASE WHEN crit.Comorbidity = 'Congestive heart failure' THEN 1 ELSE 0 END) AS CHF,
    MAX(CASE WHEN crit.Comorbidity = 'Peripheral vascular disease' THEN 1 ELSE 0 END) AS Vasc,
    MAX(CASE WHEN crit.Comorbidity = 'Renal disease' THEN 1 ELSE 0 END) AS Renal,
    MAX(CASE WHEN crit.Comorbidity = 'Solid tumor without metastases' THEN 1 ELSE 0 END) AS Tumor,
    MAX(CASE WHEN crit.Comorbidity = 'Paraplegia and hemiplegia' THEN 1 ELSE 0 END) AS Plegia,
    MAX(CASE WHEN crit.Comorbidity = 'Aspiration pneumonia' THEN 1 ELSE 0 END) AS Aspir,
    MAX(CASE WHEN crit.Comorbidity = 'Dementia' THEN 1 ELSE 0 END) AS Demen,
    MAX(CASE WHEN crit.Comorbidity = 'Brain tumor' THEN 1 ELSE 0 END) AS BrainTumor,
    MAX(CASE WHEN crit.Comorbidity = 'Anoxic brain injury' THEN 1 ELSE 0 END) AS AnoxicBrain,
    MAX(CASE WHEN crit.Comorbidity = 'Moderate or severe liver disease' THEN 1 ELSE 0 END) AS ModSevLiver,
    MAX(CASE WHEN crit.Comorbidity = 'Metastatic cancer' THEN 1 ELSE 0 END) AS MetCancer
FROM 
    CDWWork.Dim.ICD9 icd
    INNER JOIN
    #ICD9EsCriteria crit
        ON
        icd.ICD9Code LIKE crit.ICD9Prefix
WHERE
    LEN(icd.ICD9Code) <= 10
GROUP BY
    icd.ICD9SID,
    icd.ICD9Code
;

DROP TABLE IF EXISTS ORD_Haneef_202402056D.Dflt.rnEsICD10;
CREATE TABLE ORD_Haneef_202402056D.Dflt.rnEsICD10 (
    ICD10SID INT PRIMARY KEY,
    ICD10Code VARCHAR(10),
    PulmCirc BIT,
    HTN BIT,
    Arrhy BIT,
    CHF BIT,
    Vasc BIT,
    Renal BIT,
    Tumor BIT,
    Plegia BIT,
    Aspir BIT,
    Demen BIT,
    BrainTumor BIT,
    AnoxicBrain BIT,
    ModSevLiver BIT,
    MetCancer BIT
);
INSERT INTO ORD_Haneef_202402056D.Dflt.rnEsICD10 (
    ICD10SID,
    ICD10Code, 
    PulmCirc,
    HTN,
    Arrhy,
    CHF,
    Vasc,
    Renal,
    Tumor,
    Plegia,
    Aspir,
    Demen,
    BrainTumor,
    AnoxicBrain,
    ModSevLiver,
    MetCancer
)
SELECT
    icd.ICD10SID,
    icd.ICD10Code,
    MAX(CASE WHEN crit.Comorbidity = 'Pulmonary circulation disorders' THEN 1 ELSE 0 END) AS PulmCirc,
    MAX(CASE WHEN crit.Comorbidity = 'Hypertension' THEN 1 ELSE 0 END) AS HTN,
    MAX(CASE WHEN crit.Comorbidity = 'Cardiac arrhythmias' THEN 1 ELSE 0 END) AS Arrhy,
    MAX(CASE WHEN crit.Comorbidity = 'Congestive heart failure' THEN 1 ELSE 0 END) AS CHF,
    MAX(CASE WHEN crit.Comorbidity = 'Peripheral vascular disease' THEN 1 ELSE 0 END) AS Vasc,
    MAX(CASE WHEN crit.Comorbidity = 'Renal disease' THEN 1 ELSE 0 END) AS Renal,
    MAX(CASE WHEN crit.Comorbidity = 'Solid tumor without metastases' THEN 1 ELSE 0 END) AS Tumor,
    MAX(CASE WHEN crit.Comorbidity = 'Paraplegia and hemiplegia' THEN 1 ELSE 0 END) AS Plegia,
    MAX(CASE WHEN crit.Comorbidity = 'Aspiration pneumonia' THEN 1 ELSE 0 END) AS Aspir,
    MAX(CASE WHEN crit.Comorbidity = 'Dementia' THEN 1 ELSE 0 END) AS Demen,
    MAX(CASE WHEN crit.Comorbidity = 'Brain tumor' THEN 1 ELSE 0 END) AS BrainTumor,
    MAX(CASE WHEN crit.Comorbidity = 'Anoxic brain injury' THEN 1 ELSE 0 END) AS AnoxicBrain,
    MAX(CASE WHEN crit.Comorbidity = 'Moderate or severe liver disease' THEN 1 ELSE 0 END) AS ModSevLiver,
    MAX(CASE WHEN crit.Comorbidity = 'Metastatic cancer' THEN 1 ELSE 0 END) AS MetCancer
FROM 
    CDWWork.Dim.ICD10 icd
    INNER JOIN
    #ICD10EsCriteria crit
        ON
        icd.ICD10Code LIKE crit.ICD10Prefix
WHERE
    LEN(icd.ICD10Code) <= 10
GROUP BY
    icd.ICD10SID,
    icd.ICD10Code
;

