/*

This file gathers the relevant ICD codes for comorbidities found in the 
Elixhauser comorbidity index (ECI).

*/


DROP TABLE IF EXISTS #ICD9ElixhauserCriteria;
SELECT
    *
INTO
    #ICD9ElixhauserCriteria
FROM (VALUES
    ('398.91%', 'Congestive heart failure'),
    ('402.01%', 'Congestive heart failure'),
    ('402.11%', 'Congestive heart failure'),
    ('402.91%', 'Congestive heart failure'),
    ('404.01%', 'Congestive heart failure'),
    ('404.03%', 'Congestive heart failure'),
    ('404.11%', 'Congestive heart failure'),
    ('404.13%', 'Congestive heart failure'),
    ('404.91%', 'Congestive heart failure'),
    ('404.93%', 'Congestive heart failure'),
    ('425.4%', 'Congestive heart failure'),
    ('425.5%', 'Congestive heart failure'),
    ('425.6%', 'Congestive heart failure'),
    ('425.7%', 'Congestive heart failure'),
    ('425.8%', 'Congestive heart failure'),
    ('425.9%', 'Congestive heart failure'),
    ('428%', 'Congestive heart failure'),

    ('426.0%', 'Cardiac arrhythmia'),
    ('426.13%', 'Cardiac arrhythmia'),
    ('426.7%', 'Cardiac arrhythmia'),
    ('426.9%', 'Cardiac arrhythmia'),
    ('426.10%', 'Cardiac arrhythmia'),
    ('426.12%', 'Cardiac arrhythmia'),
    ('427.0%', 'Cardiac arrhythmia'),
    ('427.1%', 'Cardiac arrhythmia'),
    ('427.2%', 'Cardiac arrhythmia'),
    ('427.3%', 'Cardiac arrhythmia'),
    ('427.4%', 'Cardiac arrhythmia'),
    ('427.6%', 'Cardiac arrhythmia'),
    ('427.7%', 'Cardiac arrhythmia'),
    ('427.8%', 'Cardiac arrhythmia'),
    ('427.9%', 'Cardiac arrhythmia'),
    ('785.0%', 'Cardiac arrhythmia'),
    ('996.01%', 'Cardiac arrhythmia'),
    ('996.04%', 'Cardiac arrhythmia'),
    ('V45.0%', 'Cardiac arrhythmia'),
    ('V53.3%', 'Cardiac arrhythmia'),

    ('093.2%', 'Valvular disease'),
    ('394%', 'Valvular disease'),
    ('395%', 'Valvular disease'),
    ('396%', 'Valvular disease'),
    ('397%', 'Valvular disease'),
    ('424%', 'Valvular disease'),
    ('746.3%', 'Valvular disease'),
    ('746.4%', 'Valvular disease'),
    ('746.5%', 'Valvular disease'),
    ('746.6%', 'Valvular disease'),
    ('V42.2%', 'Valvular disease'),
    ('V43.3%', 'Valvular disease'),

    ('415.0%', 'Pulmonary circulation disorder'),
    ('415.1%', 'Pulmonary circulation disorder'),
    ('416%', 'Pulmonary circulation disorder'),
    ('417.0%', 'Pulmonary circulation disorder'),
    ('417.8%', 'Pulmonary circulation disorder'),
    ('417.9%', 'Pulmonary circulation disorder'),

    ('093.0%', 'Peripheral vascular disease'),
    ('437.3%', 'Peripheral vascular disease'),
    ('440.x%', 'Peripheral vascular disease'),
    ('441.x%', 'Peripheral vascular disease'),
    ('443.1%', 'Peripheral vascular disease'),
    ('443.2%', 'Peripheral vascular disease'),
    ('443.3%', 'Peripheral vascular disease'),
    ('443.4%', 'Peripheral vascular disease'),
    ('443.5%', 'Peripheral vascular disease'),
    ('443.6%', 'Peripheral vascular disease'),
    ('443.7%', 'Peripheral vascular disease'),
    ('443.8%', 'Peripheral vascular disease'),
    ('443.9%', 'Peripheral vascular disease'),
    ('447.1%', 'Peripheral vascular disease'),
    ('557.1%', 'Peripheral vascular disease'),
    ('557.9%', 'Peripheral vascular disease'),
    ('V43.4%', 'Peripheral vascular disease'),

    ('401%', 'Hypertension, uncomplicated'),

    ('402%', 'Hypertension, complicated'),
    ('403%', 'Hypertension, complicated'),
    ('404%', 'Hypertension, complicated'),
    ('405%', 'Hypertension, complicated'),

    ('334.1%', 'Paralysis'),
    ('342.x%', 'Paralysis'),
    ('343.x%', 'Paralysis'),
    ('344.0%', 'Paralysis'),
    ('344.1%', 'Paralysis'),
    ('344.2%', 'Paralysis'),
    ('344.3%', 'Paralysis'),
    ('344.4%', 'Paralysis'),
    ('344.5%', 'Paralysis'),
    ('344.6%', 'Paralysis'),
    ('344.9%', 'Paralysis'),

    ('331.9%', 'Other neurological disorders'),
    ('332.0%', 'Other neurological disorders'),
    ('332.1%', 'Other neurological disorders'),
    ('333.4%', 'Other neurological disorders'),
    ('333.5%', 'Other neurological disorders'),
    ('333.92%', 'Other neurological disorders'),
    ('334%', 'Other neurological disorders'),
    ('335%', 'Other neurological disorders'),
    ('336.2%', 'Other neurological disorders'),
    ('340%', 'Other neurological disorders'),
    ('341%', 'Other neurological disorders'),
    ('345%', 'Other neurological disorders'),
    ('348.1%', 'Other neurological disorders'),
    ('348.3%', 'Other neurological disorders'),
    ('780.3%', 'Other neurological disorders'),
    ('784.3%', 'Other neurological disorders'),

    ('416.8%', 'Chronic pulmonary disease'),
    ('416.9%', 'Chronic pulmonary disease'),
    ('490%', 'Chronic pulmonary disease'),
    ('491%', 'Chronic pulmonary disease'),
    ('492%', 'Chronic pulmonary disease'),
    ('493%', 'Chronic pulmonary disease'),
    ('494%', 'Chronic pulmonary disease'),
    ('495%', 'Chronic pulmonary disease'),
    ('496%', 'Chronic pulmonary disease'),
    ('497%', 'Chronic pulmonary disease'),
    ('498%', 'Chronic pulmonary disease'),
    ('499%', 'Chronic pulmonary disease'),
    ('500%', 'Chronic pulmonary disease'),
    ('501%', 'Chronic pulmonary disease'),
    ('502%', 'Chronic pulmonary disease'),
    ('503%', 'Chronic pulmonary disease'),
    ('504%', 'Chronic pulmonary disease'),
    ('505%', 'Chronic pulmonary disease'),
    ('506.4%', 'Chronic pulmonary disease'),
    ('508.1%', 'Chronic pulmonary disease'),
    ('508.8%', 'Chronic pulmonary disease'),

    ('250.0%', 'Diabetes, uncomplicated'),
    ('250.1%', 'Diabetes, uncomplicated'),
    ('250.2%', 'Diabetes, uncomplicated'),
    ('250.3%', 'Diabetes, uncomplicated'),

    ('250.4%', 'Diabetes, complicated'),
    ('250.5%', 'Diabetes, complicated'),
    ('250.6%', 'Diabetes, complicated'),
    ('250.7%', 'Diabetes, complicated'),
    ('250.8%', 'Diabetes, complicated'),
    ('250.9%', 'Diabetes, complicated'),

    ('240.9%', 'Hypothyroidism'),
    ('243%', 'Hypothyroidism'),
    ('244%', 'Hypothyroidism'),
    ('246.1%', 'Hypothyroidism'),
    ('246.8%', 'Hypothyroidism'),

    ('403.01%', 'Renal failure'),
    ('403.11%', 'Renal failure'),
    ('403.91%', 'Renal failure'),
    ('404.02%', 'Renal failure'),
    ('404.03%', 'Renal failure'),
    ('404.12%', 'Renal failure'),
    ('404.13%', 'Renal failure'),
    ('404.92%', 'Renal failure'),
    ('404.93%', 'Renal failure'),
    ('585%', 'Renal failure'),
    ('586%', 'Renal failure'),
    ('588.0%', 'Renal failure'),
    ('V42.0%', 'Renal failure'),
    ('V45.1%', 'Renal failure'),
    ('V56%', 'Renal failure'),

    ('070.22%', 'Liver disease'),
    ('070.23%', 'Liver disease'),
    ('070.32%', 'Liver disease'),
    ('070.33%', 'Liver disease'),
    ('070.44%', 'Liver disease'),
    ('070.54%', 'Liver disease'),
    ('070.6%', 'Liver disease'),
    ('070.9%', 'Liver disease'),
    ('456.0%', 'Liver disease'),
    ('456.1%', 'Liver disease'),
    ('456.2%', 'Liver disease'),
    ('570%', 'Liver disease'),
    ('571%', 'Liver disease'),
    ('572.2%', 'Liver disease'),
    ('572.3%', 'Liver disease'),
    ('572.4%', 'Liver disease'),
    ('572.5%', 'Liver disease'),
    ('572.6%', 'Liver disease'),
    ('572.7%', 'Liver disease'),
    ('572.8%', 'Liver disease'),
    ('573.3%', 'Liver disease'),
    ('573.4%', 'Liver disease'),
    ('573.8%', 'Liver disease'),
    ('573.9%', 'Liver disease'),
    ('V42.7%', 'Liver disease'),

    ('531.7%', 'Peptic ulcer disease excluding bleeding'),
    ('531.9%', 'Peptic ulcer disease excluding bleeding'),
    ('532.7%', 'Peptic ulcer disease excluding bleeding'),
    ('532.9%', 'Peptic ulcer disease excluding bleeding'),
    ('533.7%', 'Peptic ulcer disease excluding bleeding'),
    ('533.9%', 'Peptic ulcer disease excluding bleeding'),
    ('534.7%', 'Peptic ulcer disease excluding bleeding'),
    ('534.9%', 'Peptic ulcer disease excluding bleeding'),

    ('042%', 'AIDS/HIV'),
    ('043%', 'AIDS/HIV'),
    ('044%', 'AIDS/HIV'),

    ('200%', 'Lymphoma'),
    ('201%', 'Lymphoma'),
    ('202%', 'Lymphoma'),
    ('203.0%', 'Lymphoma'),
    ('238.6%', 'Lymphoma'),

    ('196%', 'Metastatic cancer'),
    ('197%', 'Metastatic cancer'),
    ('198%', 'Metastatic cancer'),
    ('199%', 'Metastatic cancer'),

    ('140%', 'Solid tumor without metastasis'),
    ('141%', 'Solid tumor without metastasis'),
    ('142%', 'Solid tumor without metastasis'),
    ('143%', 'Solid tumor without metastasis'),
    ('144%', 'Solid tumor without metastasis'),
    ('145%', 'Solid tumor without metastasis'),
    ('146%', 'Solid tumor without metastasis'),
    ('147%', 'Solid tumor without metastasis'),
    ('148%', 'Solid tumor without metastasis'),
    ('149%', 'Solid tumor without metastasis'),
    ('150%', 'Solid tumor without metastasis'),
    ('151%', 'Solid tumor without metastasis'),
    ('152%', 'Solid tumor without metastasis'),
    ('153%', 'Solid tumor without metastasis'),
    ('154%', 'Solid tumor without metastasis'),
    ('155%', 'Solid tumor without metastasis'),
    ('156%', 'Solid tumor without metastasis'),
    ('157%', 'Solid tumor without metastasis'),
    ('158%', 'Solid tumor without metastasis'),
    ('159%', 'Solid tumor without metastasis'),
    ('160%', 'Solid tumor without metastasis'),
    ('161%', 'Solid tumor without metastasis'),
    ('162%', 'Solid tumor without metastasis'),
    ('163%', 'Solid tumor without metastasis'),
    ('164%', 'Solid tumor without metastasis'),
    ('165%', 'Solid tumor without metastasis'),
    ('166%', 'Solid tumor without metastasis'),
    ('167%', 'Solid tumor without metastasis'),
    ('168%', 'Solid tumor without metastasis'),
    ('169%', 'Solid tumor without metastasis'),
    ('170%', 'Solid tumor without metastasis'),
    ('171%', 'Solid tumor without metastasis'),
    ('172%', 'Solid tumor without metastasis'),
    ('174%', 'Solid tumor without metastasis'),
    ('175%', 'Solid tumor without metastasis'),
    ('176%', 'Solid tumor without metastasis'),
    ('177%', 'Solid tumor without metastasis'),
    ('178%', 'Solid tumor without metastasis'),
    ('179%', 'Solid tumor without metastasis'),
    ('180%', 'Solid tumor without metastasis'),
    ('181%', 'Solid tumor without metastasis'),
    ('182%', 'Solid tumor without metastasis'),
    ('183%', 'Solid tumor without metastasis'),
    ('184%', 'Solid tumor without metastasis'),
    ('185%', 'Solid tumor without metastasis'),
    ('186%', 'Solid tumor without metastasis'),
    ('187%', 'Solid tumor without metastasis'),
    ('188%', 'Solid tumor without metastasis'),
    ('189%', 'Solid tumor without metastasis'),
    ('190%', 'Solid tumor without metastasis'),
    ('191%', 'Solid tumor without metastasis'),
    ('192%', 'Solid tumor without metastasis'),
    ('193%', 'Solid tumor without metastasis'),
    ('194%', 'Solid tumor without metastasis'),
    ('195%', 'Solid tumor without metastasis'),

    ('446%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('701.0%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('710.0%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('710.1%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('710.2%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('710.3%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('710.4%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('710.8%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('710.9%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('711.2%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('714%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('719.3%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('720%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('725%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('728.5%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('728.89%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('729.30%', 'Rheumatoid arthritis/collagen vascular diseases'),

    ('286%', 'Coagulopathy'),
    ('287.1%', 'Coagulopathy'),
    ('287.3%', 'Coagulopathy'),
    ('287.4%', 'Coagulopathy'),
    ('287.5%', 'Coagulopathy'),

    ('278.0%', 'Obesity'),

    ('260%', 'Weight loss'),
    ('261%', 'Weight loss'),
    ('262%', 'Weight loss'),
    ('263%', 'Weight loss'),

    ('276.0%', 'Fluid and electrolyte disorders'),
    ('276.1%', 'Fluid and electrolyte disorders'),
    ('276.2%', 'Fluid and electrolyte disorders'),
    ('276.3%', 'Fluid and electrolyte disorders'),
    ('276.4%', 'Fluid and electrolyte disorders'),
    ('276.5%', 'Fluid and electrolyte disorders'),
    ('276.6%', 'Fluid and electrolyte disorders'),
    ('276.7%', 'Fluid and electrolyte disorders'),
    ('276.8%', 'Fluid and electrolyte disorders'),
    ('276.9%', 'Fluid and electrolyte disorders'),

    ('280.0%', 'Blood-loss anemia'),

    ('280.1%', 'Deficiency anemia'),
    ('280.2%', 'Deficiency anemia'),
    ('280.3%', 'Deficiency anemia'),
    ('280.4%', 'Deficiency anemia'),
    ('280.5%', 'Deficiency anemia'),
    ('280.6%', 'Deficiency anemia'),
    ('280.7%', 'Deficiency anemia'),
    ('280.8%', 'Deficiency anemia'),
    ('280.9%', 'Deficiency anemia'),
    ('281%', 'Deficiency anemia'),

    ('265.2%', 'Alcohol abuse'),
    ('291.1%', 'Alcohol abuse'),
    ('291.2%', 'Alcohol abuse'),
    ('291.3%', 'Alcohol abuse'),
    ('291.5%', 'Alcohol abuse'),
    ('291.6%', 'Alcohol abuse'),
    ('291.7%', 'Alcohol abuse'),
    ('291.8%', 'Alcohol abuse'),
    ('291.9%', 'Alcohol abuse'),
    ('303.0%', 'Alcohol abuse'),
    ('303.9%', 'Alcohol abuse'),
    ('305.0%', 'Alcohol abuse'),
    ('357.5%', 'Alcohol abuse'),
    ('425.5%', 'Alcohol abuse'),
    ('535.3%', 'Alcohol abuse'),
    ('571.0%', 'Alcohol abuse'),
    ('571.1%', 'Alcohol abuse'),
    ('571.2%', 'Alcohol abuse'),
    ('571.3%', 'Alcohol abuse'),
    ('980%', 'Alcohol abuse'),
    ('V11.3%', 'Alcohol abuse'),

    ('292%', 'Drug abuse'),
    ('304%', 'Drug abuse'),
    ('305.2%', 'Drug abuse'),
    ('305.3%', 'Drug abuse'),
    ('305.4%', 'Drug abuse'),
    ('305.5%', 'Drug abuse'),
    ('305.6%', 'Drug abuse'),
    ('305.7%', 'Drug abuse'),
    ('305.8%', 'Drug abuse'),
    ('305.9%', 'Drug abuse'),
    ('V65.42%', 'Drug abuse'),

    ('293.8%', 'Psychoses'),
    ('295%', 'Psychoses'),
    ('296.04%', 'Psychoses'),
    ('296.14%', 'Psychoses'),
    ('296.44%', 'Psychoses'),
    ('296.54%', 'Psychoses'),
    ('297%', 'Psychoses'),
    ('298%', 'Psychoses'),

    ('296.2%', 'Depression'),
    ('296.3%', 'Depression'),
    ('296.5%', 'Depression'),
    ('300.4%', 'Depression'),
    ('309%', 'Depression'),
    ('311%', 'Depression')
) AS criteria (ICD9Prefix, Comorbidity)
;

DROP TABLE IF EXISTS #ICD10ElixhauserCriteria;
SELECT
    *
INTO
    #ICD10ElixhauserCriteria
FROM (VALUES
    ('I09.9%', 'Congestive heart failure'),
    ('I11.0%', 'Congestive heart failure'),
    ('I13.0%', 'Congestive heart failure'),
    ('I13.2%', 'Congestive heart failure'),
    ('I25.5%', 'Congestive heart failure'),
    ('I42.0%', 'Congestive heart failure'),
    ('I42.5%', 'Congestive heart failure'),
    ('I42.6%', 'Congestive heart failure'),
    ('I42.7%', 'Congestive heart failure'),
    ('I42.8%', 'Congestive heart failure'),
    ('I42.9%', 'Congestive heart failure'),
    ('I43%', 'Congestive heart failure'),
    ('I50%', 'Congestive heart failure'),
    ('P29.0%', 'Congestive heart failure'),

    ('I44.1%', 'Cardiac arrhythmia'),
    ('I44.2%', 'Cardiac arrhythmia'),
    ('I44.3%', 'Cardiac arrhythmia'),
    ('I45.6%', 'Cardiac arrhythmia'),
    ('I45.9%', 'Cardiac arrhythmia'),
    ('I47%', 'Cardiac arrhythmia'),
    ('I48%', 'Cardiac arrhythmia'),
    ('I49%', 'Cardiac arrhythmia'),
    ('R00.0%', 'Cardiac arrhythmia'),
    ('R00.1%', 'Cardiac arrhythmia'),
    ('R00.8%', 'Cardiac arrhythmia'),
    ('T82.1%', 'Cardiac arrhythmia'),
    ('Z45.0%', 'Cardiac arrhythmia'),
    ('Z95.0%', 'Cardiac arrhythmia'),

    ('A52.0%', 'Valvular disease'),
    ('I05%', 'Valvular disease'),
    ('I06%', 'Valvular disease'),
    ('I07%', 'Valvular disease'),
    ('I08%', 'Valvular disease'),
    ('I09.1%', 'Valvular disease'),
    ('I09.8%', 'Valvular disease'),
    ('I34%', 'Valvular disease'),
    ('I35%', 'Valvular disease'),
    ('I36%', 'Valvular disease'),
    ('I37%', 'Valvular disease'),
    ('I38%', 'Valvular disease'),
    ('I39%', 'Valvular disease'),
    ('Q23.0%', 'Valvular disease'),
    ('Q23.1%', 'Valvular disease'),
    ('Q23.2%', 'Valvular disease'),
    ('Q23.3%', 'Valvular disease'),
    ('Z95.2%', 'Valvular disease'),
    ('Z95.3%', 'Valvular disease'),
    ('Z95.4%', 'Valvular disease'),

    ('I26%', 'Pulmonary circulation disorder'),
    ('I27%', 'Pulmonary circulation disorder'),
    ('I28.0%', 'Pulmonary circulation disorder'),
    ('I28.8%', 'Pulmonary circulation disorder'),
    ('I28.9%', 'Pulmonary circulation disorder'),

    ('I70%', 'Peripheral vascular disease'),
    ('I71%', 'Peripheral vascular disease'),
    ('I73.1%', 'Peripheral vascular disease'),
    ('I73.8%', 'Peripheral vascular disease'),
    ('I73.9%', 'Peripheral vascular disease'),
    ('I77.1%', 'Peripheral vascular disease'),
    ('I79.0%', 'Peripheral vascular disease'),
    ('I79.2%', 'Peripheral vascular disease'),
    ('K55.1%', 'Peripheral vascular disease'),
    ('K55.8%', 'Peripheral vascular disease'),
    ('K55.9%', 'Peripheral vascular disease'),
    ('Z95.8%', 'Peripheral vascular disease'),
    ('Z95.9%', 'Peripheral vascular disease'),

    ('I10%', 'Hypertension, uncomplicated'),
    ('I11%', 'Hypertension, complicated'),
    ('I12%', 'Hypertension, complicated'),
    ('I13%', 'Hypertension, complicated'),
    ('I15%', 'Hypertension, complicated'),

    ('G04.1%', 'Paralysis'),
    ('G11.4%', 'Paralysis'),
    ('G80.1%', 'Paralysis'),
    ('G80.2%', 'Paralysis'),
    ('G81%', 'Paralysis'),
    ('G82%', 'Paralysis'),
    ('G83.0%', 'Paralysis'),
    ('G83.1%', 'Paralysis'),
    ('G83.2%', 'Paralysis'),
    ('G83.3%', 'Paralysis'),
    ('G83.4%', 'Paralysis'),
    ('G83.9%', 'Paralysis'),

    ('G10%', 'Other neurological disorders'),
    ('G11%', 'Other neurological disorders'),
    ('G12%', 'Other neurological disorders'),
    ('G13%', 'Other neurological disorders'),
    ('G20%', 'Other neurological disorders'),
    ('G21%', 'Other neurological disorders'),
    ('G22%', 'Other neurological disorders'),
    ('G25.4%', 'Other neurological disorders'),
    ('G25.5%', 'Other neurological disorders'),
    ('G31.2%', 'Other neurological disorders'),
    ('G31.8%', 'Other neurological disorders'),
    ('G31.9%', 'Other neurological disorders'),
    ('G32%', 'Other neurological disorders'),
    ('G35%', 'Other neurological disorders'),
    ('G36%', 'Other neurological disorders'),
    ('G37%', 'Other neurological disorders'),
    ('G40%', 'Other neurological disorders'),
    ('G41%', 'Other neurological disorders'),
    ('G93.1%', 'Other neurological disorders'),
    ('G93.4%', 'Other neurological disorders'),
    ('R47.0%', 'Other neurological disorders'),
    ('R56%', 'Other neurological disorders'),

    ('I27.8%', 'Chronic pulmonary disease'),
    ('I27.9%', 'Chronic pulmonary disease'),
    ('J40%', 'Chronic pulmonary disease'),
    ('J41%', 'Chronic pulmonary disease'),
    ('J42%', 'Chronic pulmonary disease'),
    ('J43%', 'Chronic pulmonary disease'),
    ('J44%', 'Chronic pulmonary disease'),
    ('J45%', 'Chronic pulmonary disease'),
    ('J46%', 'Chronic pulmonary disease'),
    ('J47%', 'Chronic pulmonary disease'),
    ('J60%', 'Chronic pulmonary disease'),
    ('J61%', 'Chronic pulmonary disease'),
    ('J62%', 'Chronic pulmonary disease'),
    ('J63%', 'Chronic pulmonary disease'),
    ('J64%', 'Chronic pulmonary disease'),
    ('J65%', 'Chronic pulmonary disease'),
    ('J66%', 'Chronic pulmonary disease'),
    ('J67%', 'Chronic pulmonary disease'),
    ('J68.4%', 'Chronic pulmonary disease'),
    ('J70.1%', 'Chronic pulmonary disease'),
    ('J70.3%', 'Chronic pulmonary disease'),

    ('E10.0%', 'Diabetes, uncomplicated'),
    ('E10.1%', 'Diabetes, uncomplicated'),
    ('E10.9%', 'Diabetes, uncomplicated'),
    ('E11.0%', 'Diabetes, uncomplicated'),
    ('E11.1%', 'Diabetes, uncomplicated'),
    ('E11.9%', 'Diabetes, uncomplicated'),
    ('E12.0%', 'Diabetes, uncomplicated'),
    ('E12.1%', 'Diabetes, uncomplicated'),
    ('E12.9%', 'Diabetes, uncomplicated'),
    ('E13.0%', 'Diabetes, uncomplicated'),
    ('E13.1%', 'Diabetes, uncomplicated'),
    ('E13.9%', 'Diabetes, uncomplicated'),
    ('E14.0%', 'Diabetes, uncomplicated'),
    ('E14.1%', 'Diabetes, uncomplicated'),
    ('E14.9%', 'Diabetes, uncomplicated'),

    ('E10.2%', 'Diabetes, complicated'),
    ('E10.3%', 'Diabetes, complicated'),
    ('E10.4%', 'Diabetes, complicated'),
    ('E10.5%', 'Diabetes, complicated'),
    ('E10.6%', 'Diabetes, complicated'),
    ('E10.7%', 'Diabetes, complicated'),
    ('E10.8%', 'Diabetes, complicated'),
    ('E11.2%', 'Diabetes, complicated'),
    ('E11.3%', 'Diabetes, complicated'),
    ('E11.4%', 'Diabetes, complicated'),
    ('E11.5%', 'Diabetes, complicated'),
    ('E11.6%', 'Diabetes, complicated'),
    ('E11.7%', 'Diabetes, complicated'),
    ('E11.8%', 'Diabetes, complicated'),
    ('E12.2%', 'Diabetes, complicated'),
    ('E12.3%', 'Diabetes, complicated'),
    ('E12.4%', 'Diabetes, complicated'),
    ('E12.5%', 'Diabetes, complicated'),
    ('E12.6%', 'Diabetes, complicated'),
    ('E12.7%', 'Diabetes, complicated'),
    ('E12.8%', 'Diabetes, complicated'),
    ('E13.2%', 'Diabetes, complicated'),
    ('E13.3%', 'Diabetes, complicated'),
    ('E13.4%', 'Diabetes, complicated'),
    ('E13.5%', 'Diabetes, complicated'),
    ('E13.6%', 'Diabetes, complicated'),
    ('E13.7%', 'Diabetes, complicated'),
    ('E13.8%', 'Diabetes, complicated'),
    ('E14.2%', 'Diabetes, complicated'),
    ('E14.3%', 'Diabetes, complicated'),
    ('E14.4%', 'Diabetes, complicated'),
    ('E14.5%', 'Diabetes, complicated'),
    ('E14.6%', 'Diabetes, complicated'),
    ('E14.7%', 'Diabetes, complicated'),
    ('E14.8%', 'Diabetes, complicated'),

    ('E00%', 'Hypothyroidism'),
    ('E01%', 'Hypothyroidism'),
    ('E02%', 'Hypothyroidism'),
    ('E03%', 'Hypothyroidism'),
    ('E89.0%', 'Hypothyroidism'),

    ('I12.0%', 'Renal failure'),
    ('I13.1%', 'Renal failure'),
    ('N25.0%', 'Renal failure'),
    ('Z49.0%', 'Renal failure'),
    ('Z49.1%', 'Renal failure'),
    ('Z49.2%', 'Renal failure'),
    ('Z94.0%', 'Renal failure'),
    ('Z99.2%', 'Renal failure'),
    ('N18%', 'Renal failure'),
    ('N18%', 'Renal failure'),

    ('B18%', 'Liver disease'),
    ('I85%', 'Liver disease'),
    ('I86.4%', 'Liver disease'),
    ('I98.2%', 'Liver disease'),
    ('K70%', 'Liver disease'),
    ('K71.1%', 'Liver disease'),
    ('K71.3%', 'Liver disease'),
    ('K71.4%', 'Liver disease'),
    ('K71.5%', 'Liver disease'),
    ('K71.7%', 'Liver disease'),
    ('K72%', 'Liver disease'),
    ('K73%', 'Liver disease'),
    ('K74%', 'Liver disease'),
    ('K76.0%', 'Liver disease'),
    ('K76.2%', 'Liver disease'),
    ('K76.3%', 'Liver disease'),
    ('K76.4%', 'Liver disease'),
    ('K76.5%', 'Liver disease'),
    ('K76.6%', 'Liver disease'),
    ('K76.7%', 'Liver disease'),
    ('K76.8%', 'Liver disease'),
    ('K76.9%', 'Liver disease'),
    ('Z94.4%', 'Liver disease'),

    ('K25.7%', 'Peptic ulcer disease excluding bleeding'),
    ('K25.9%', 'Peptic ulcer disease excluding bleeding'),
    ('K26.7%', 'Peptic ulcer disease excluding bleeding'),
    ('K26.9%', 'Peptic ulcer disease excluding bleeding'),
    ('K27.7%', 'Peptic ulcer disease excluding bleeding'),
    ('K27.9%', 'Peptic ulcer disease excluding bleeding'),
    ('K28.7%', 'Peptic ulcer disease excluding bleeding'),
    ('K28.9%', 'Peptic ulcer disease excluding bleeding'),

    ('B20%', 'AIDS/HIV'),
    ('B21%', 'AIDS/HIV'),
    ('B22%', 'AIDS/HIV'),
    ('B24%', 'AIDS/HIV'),

    ('C81%', 'Lymphoma'),
    ('C82%', 'Lymphoma'),
    ('C83%', 'Lymphoma'),
    ('C84%', 'Lymphoma'),
    ('C85%', 'Lymphoma'),
    ('C88%', 'Lymphoma'),
    ('C96%', 'Lymphoma'),
    ('C90.0%', 'Lymphoma'),
    ('C90.2%', 'Lymphoma'),

    ('C77%', 'Metastatic cancer'),
    ('C78%', 'Metastatic cancer'),
    ('C79%', 'Metastatic cancer'),
    ('C80%', 'Metastatic cancer'),

    ('C00%', 'Solid tumor without metastasis'),
    ('C01%', 'Solid tumor without metastasis'),
    ('C02%', 'Solid tumor without metastasis'),
    ('C03%', 'Solid tumor without metastasis'),
    ('C04%', 'Solid tumor without metastasis'),
    ('C05%', 'Solid tumor without metastasis'),
    ('C06%', 'Solid tumor without metastasis'),
    ('C07%', 'Solid tumor without metastasis'),
    ('C08%', 'Solid tumor without metastasis'),
    ('C09%', 'Solid tumor without metastasis'),
    ('C10%', 'Solid tumor without metastasis'),
    ('C11%', 'Solid tumor without metastasis'),
    ('C12%', 'Solid tumor without metastasis'),
    ('C13%', 'Solid tumor without metastasis'),
    ('C14%', 'Solid tumor without metastasis'),
    ('C15%', 'Solid tumor without metastasis'),
    ('C16%', 'Solid tumor without metastasis'),
    ('C17%', 'Solid tumor without metastasis'),
    ('C18%', 'Solid tumor without metastasis'),
    ('C19%', 'Solid tumor without metastasis'),
    ('C20%', 'Solid tumor without metastasis'),
    ('C21%', 'Solid tumor without metastasis'),
    ('C22%', 'Solid tumor without metastasis'),
    ('C23%', 'Solid tumor without metastasis'),
    ('C24%', 'Solid tumor without metastasis'),
    ('C25%', 'Solid tumor without metastasis'),
    ('C26%', 'Solid tumor without metastasis'),
    ('C30%', 'Solid tumor without metastasis'),
    ('C31%', 'Solid tumor without metastasis'),
    ('C32%', 'Solid tumor without metastasis'),
    ('C33%', 'Solid tumor without metastasis'),
    ('C34%', 'Solid tumor without metastasis'),
    ('C37%', 'Solid tumor without metastasis'),
    ('C38%', 'Solid tumor without metastasis'),
    ('C39%', 'Solid tumor without metastasis'),
    ('C40%', 'Solid tumor without metastasis'),
    ('C41%', 'Solid tumor without metastasis'),
    ('C43%', 'Solid tumor without metastasis'),
    ('C45%', 'Solid tumor without metastasis'),
    ('C46%', 'Solid tumor without metastasis'),
    ('C47%', 'Solid tumor without metastasis'),
    ('C48%', 'Solid tumor without metastasis'),
    ('C49%', 'Solid tumor without metastasis'),
    ('C50%', 'Solid tumor without metastasis'),
    ('C51%', 'Solid tumor without metastasis'),
    ('C52%', 'Solid tumor without metastasis'),
    ('C53%', 'Solid tumor without metastasis'),
    ('C54%', 'Solid tumor without metastasis'),
    ('C55%', 'Solid tumor without metastasis'),
    ('C56%', 'Solid tumor without metastasis'),
    ('C57%', 'Solid tumor without metastasis'),
    ('C58%', 'Solid tumor without metastasis'),
    ('C60%', 'Solid tumor without metastasis'),
    ('C61%', 'Solid tumor without metastasis'),
    ('C62%', 'Solid tumor without metastasis'),
    ('C63%', 'Solid tumor without metastasis'),
    ('C64%', 'Solid tumor without metastasis'),
    ('C65%', 'Solid tumor without metastasis'),
    ('C66%', 'Solid tumor without metastasis'),
    ('C67%', 'Solid tumor without metastasis'),
    ('C68%', 'Solid tumor without metastasis'),
    ('C69%', 'Solid tumor without metastasis'),
    ('C70%', 'Solid tumor without metastasis'),
    ('C71%', 'Solid tumor without metastasis'),
    ('C72%', 'Solid tumor without metastasis'),
    ('C73%', 'Solid tumor without metastasis'),
    ('C74%', 'Solid tumor without metastasis'),
    ('C75%', 'Solid tumor without metastasis'),
    ('C76%', 'Solid tumor without metastasis'),
    ('C97%', 'Solid tumor without metastasis'),

    ('L94.0%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('L94.1%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('L94.3%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M05%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M06%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M08%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M12.0%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M12.3%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M30%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M31.0%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M31.1%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M31.2%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M31.3%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M32%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M33%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M34%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M35%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M45%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M46.1%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M46.8%', 'Rheumatoid arthritis/collagen vascular diseases'),
    ('M46.9%', 'Rheumatoid arthritis/collagen vascular diseases'),

    ('D65%', 'Coagulopathy'),
    ('D66%', 'Coagulopathy'),
    ('D67%', 'Coagulopathy'),
    ('D68%', 'Coagulopathy'),
    ('D69.1%', 'Coagulopathy'),
    ('D69.3%', 'Coagulopathy'),
    ('D69.4%', 'Coagulopathy'),
    ('D69.5%', 'Coagulopathy'),
    ('D69.6%', 'Coagulopathy'),

    ('E66%', 'Obesity'),

    ('E40%', 'Weight loss'),
    ('E41%', 'Weight loss'),
    ('E42%', 'Weight loss'),
    ('E43%', 'Weight loss'),
    ('E44%', 'Weight loss'),
    ('E45%', 'Weight loss'),
    ('E46%', 'Weight loss'),
    ('R63.4%', 'Weight loss'),
    ('R64%', 'Weight loss'),

    ('E22.2%', 'Fluid and electrolyte disorders'),
    ('E86%', 'Fluid and electrolyte disorders'),
    ('E87%', 'Fluid and electrolyte disorders'),

    ('D50.0%', 'Blood-loss anemia'),
    ('D50.8%', 'Deficiency anemia'),
    ('D50.9%', 'Deficiency anemia'),
    ('D51%', 'Deficiency anemia'),
    ('D52%', 'Deficiency anemia'),
    ('D53%', 'Deficiency anemia'),

    ('F10%', 'Alcohol abuse'),
    ('E52%', 'Alcohol abuse'),
    ('G62.1%', 'Alcohol abuse'),
    ('I42.6%', 'Alcohol abuse'),
    ('K29.2%', 'Alcohol abuse'),
    ('K70.0%', 'Alcohol abuse'),
    ('K70.3%', 'Alcohol abuse'),
    ('K70.9%', 'Alcohol abuse'),
    ('T51%', 'Alcohol abuse'),
    ('Z50.2%', 'Alcohol abuse'),
    ('Z71.4%', 'Alcohol abuse'),
    ('Z72.1%', 'Alcohol abuse'),

    ('F11%', 'Drug abuse'),
    ('F12%', 'Drug abuse'),
    ('F13%', 'Drug abuse'),
    ('F14%', 'Drug abuse'),
    ('F15%', 'Drug abuse'),
    ('F16%', 'Drug abuse'),
    ('F18%', 'Drug abuse'),
    ('F19%', 'Drug abuse'),
    ('Z71.5%', 'Drug abuse'),
    ('Z72.2%', 'Drug abuse'),

    ('F20%', 'Psychoses'),
    ('F22%', 'Psychoses'),
    ('F23%', 'Psychoses'),
    ('F24%', 'Psychoses'),
    ('F25%', 'Psychoses'),
    ('F28%', 'Psychoses'),
    ('F29%', 'Psychoses'),
    ('F30.2%', 'Psychoses'),
    ('F31.2%', 'Psychoses'),
    ('F31.5%', 'Psychoses'),

    ('F20.4%', 'Depression'),
    ('F31.3%', 'Depression'),
    ('F31.4%', 'Depression'),
    ('F31.5%', 'Depression'),
    ('F32%', 'Depression'),
    ('F33%', 'Depression'),
    ('F34.1%', 'Depression'),
    ('F41.2%', 'Depression'),
    ('F43.2%', 'Depression')
) AS criteria (ICD10Prefix, Comorbidity)
;

DROP TABLE IF EXISTS SCS_EEGUtil.EEG.rnElixhauserICD9;
CREATE TABLE SCS_EEGUtil.EEG.rnElixhauserICD9 (
    ICD9SID INT PRIMARY KEY,
    ICD9Code VARCHAR(10),
    CHF BIT,
    Arrhy BIT,
    Valv BIT,
    PulmCirc BIT,
    Vasc BIT,
    HTN BIT,
    Para BIT,
    Neuro BIT,
    PulmChronic BIT,
    DiabUnc BIT,
    DiabC BIT,
    Hypothy BIT,
    RenFail BIT,
    Liver BIT,
    Peptic BIT,
    AIDS BIT,
    Lymphoma BIT,
    MetCancer BIT,
    Tumor BIT,
    Rheum BIT,
    Coag BIT,
    Obesity BIT,
    WLoss BIT,
    Fluid BIT,
    Blood BIT,
    Deficiency BIT,
    Alcohol BIT,
    Drug BIT,
    Psych BIT,
    Depress BIT
);
INSERT INTO SCS_EEGUtil.EEG.rnElixhauserICD9 (
    ICD9SID,
    ICD9Code, 
    CHF,
    Arrhy,
    Valv,
    PulmCirc,
    Vasc,
    HTN,
    Para,
    Neuro,
    PulmChronic,
    DiabUnc,
    DiabC,
    Hypothy,
    RenFail,
    Liver,
    Peptic,
    AIDS,
    Lymphoma,
    MetCancer,
    Tumor,
    Rheum,
    Coag,
    Obesity,
    WLoss,
    Fluid,
    Blood,
    Deficiency,
    Alcohol,
    Drug,
    Psych,
    Depress
)
SELECT
    icd.ICD9SID,
    icd.ICD9Code,
    MAX(CASE WHEN crit.Comorbidity = 'Congestive heart failure' THEN 1 ELSE 0 END) AS CHF,
    MAX(CASE WHEN crit.Comorbidity = 'Cardiac arrhythmia' THEN 1 ELSE 0 END) AS Arrhy,
    MAX(CASE WHEN crit.Comorbidity = 'Valvular disease' THEN 1 ELSE 0 END) AS Valv,
    MAX(CASE WHEN crit.Comorbidity = 'Pulmonary circulation disorder' THEN 1 ELSE 0 END) AS PulmCirc,
    MAX(CASE WHEN crit.Comorbidity = 'Peripheral vascular disease' THEN 1 ELSE 0 END) AS Vasc,
    MAX(CASE 
        WHEN crit.Comorbidity = 'Hypertension, uncomplicated' THEN 1 
        WHEN crit.Comorbidity = 'Hypertension, complicated' THEN 1 
        ELSE 0
    END) AS HTN,
    MAX(CASE WHEN crit.Comorbidity = 'Paralysis' THEN 1 ELSE 0 END) AS Para,
    MAX(CASE WHEN crit.Comorbidity = 'Other neurological disorders' THEN 1 ELSE 0 END) AS Neuro,
    MAX(CASE WHEN crit.Comorbidity = 'Chronic pulmonary disease' THEN 1 ELSE 0 END) AS PulmChronic,
    MAX(CASE WHEN crit.Comorbidity = 'Diabetes, uncomplicated' THEN 1 ELSE 0 END) AS DiabUnc,
    MAX(CASE WHEN crit.Comorbidity = 'Diabetes, complicated' THEN 1 ELSE 0 END) AS DiabC,
    MAX(CASE WHEN crit.Comorbidity = 'Hypothyroidism' THEN 1 ELSE 0 END) AS Hypothy,
    MAX(CASE WHEN crit.Comorbidity = 'Renal failure' THEN 1 ELSE 0 END) AS RenFail,
    MAX(CASE WHEN crit.Comorbidity = 'Liver disease' THEN 1 ELSE 0 END) AS Liver,
    MAX(CASE WHEN crit.Comorbidity = 'Peptic ulcer disease excluding bleeding' THEN 1 ELSE 0 END) AS Peptic,
    MAX(CASE WHEN crit.Comorbidity = 'AIDS/HIV' THEN 1 ELSE 0 END) AS AIDS,
    MAX(CASE WHEN crit.Comorbidity = 'Lymphoma' THEN 1 ELSE 0 END) AS Lymphoma,
    MAX(CASE WHEN crit.Comorbidity = 'Metastatic cancer' THEN 1 ELSE 0 END) AS MetCancer,
    MAX(CASE WHEN crit.Comorbidity = 'Solid tumor without metastasis' THEN 1 ELSE 0 END) AS Tumor,
    MAX(CASE WHEN crit.Comorbidity = 'Rheumatoid arthritis/collagen vascular diseases' THEN 1 ELSE 0 END) AS Rheum,
    MAX(CASE WHEN crit.Comorbidity = 'Coagulopathy' THEN 1 ELSE 0 END) AS Coag,
    MAX(CASE WHEN crit.Comorbidity = 'Obesity' THEN 1 ELSE 0 END) AS Obesity,
    MAX(CASE WHEN crit.Comorbidity = 'Weight loss' THEN 1 ELSE 0 END) AS WLoss,
    MAX(CASE WHEN crit.Comorbidity = 'Fluid and electrolyte disorders' THEN 1 ELSE 0 END) AS Fluid,
    MAX(CASE WHEN crit.Comorbidity = 'Blood-loss anemia' THEN 1 ELSE 0 END) AS Blood,
    MAX(CASE WHEN crit.Comorbidity = 'Deficiency anemia' THEN 1 ELSE 0 END) AS Deficiency,
    MAX(CASE WHEN crit.Comorbidity = 'Alcohol abuse' THEN 1 ELSE 0 END) AS Alcohol,
    MAX(CASE WHEN crit.Comorbidity = 'Drug abuse' THEN 1 ELSE 0 END) AS Drug,
    MAX(CASE WHEN crit.Comorbidity = 'Psychoses' THEN 1 ELSE 0 END) AS Psych,
    MAX(CASE WHEN crit.Comorbidity = 'Depression' THEN 1 ELSE 0 END) AS Depress
FROM 
    CDWWork.Dim.ICD9 icd
    INNER JOIN
    #ICD9ElixhauserCriteria crit
        ON
        icd.ICD9Code LIKE crit.ICD9Prefix
WHERE
    LEN(icd.ICD9Code) <= 10
GROUP BY
    icd.ICD9SID,
    icd.ICD9Code
;

DROP TABLE IF EXISTS SCS_EEGUtil.EEG.rnElixhauserICD10;
CREATE TABLE SCS_EEGUtil.EEG.rnElixhauserICD10 (
    ICD10SID INT PRIMARY KEY,
    ICD10Code VARCHAR(10),
    CHF BIT,
    Arrhy BIT,
    Valv BIT,
    PulmCirc BIT,
    Vasc BIT,
    HTN BIT,
    Para BIT,
    Neuro BIT,
    PulmChronic BIT,
    DiabUnc BIT,
    DiabC BIT,
    Hypothy BIT,
    RenFail BIT,
    Liver BIT,
    Peptic BIT,
    AIDS BIT,
    Lymphoma BIT,
    MetCancer BIT,
    Tumor BIT,
    Rheum BIT,
    Coag BIT,
    Obesity BIT,
    WLoss BIT,
    Fluid BIT,
    Blood BIT,
    Deficiency BIT,
    Alcohol BIT,
    Drug BIT,
    Psych BIT,
    Depress BIT
);
INSERT INTO SCS_EEGUtil.EEG.rnElixhauserICD10 (
    ICD10SID,
    ICD10Code, 
    CHF,
    Arrhy,
    Valv,
    PulmCirc,
    Vasc,
    HTN,
    Para,
    Neuro,
    PulmChronic,
    DiabUnc,
    DiabC,
    Hypothy,
    RenFail,
    Liver,
    Peptic,
    AIDS,
    Lymphoma,
    MetCancer,
    Tumor,
    Rheum,
    Coag,
    Obesity,
    WLoss,
    Fluid,
    Blood,
    Deficiency,
    Alcohol,
    Drug,
    Psych,
    Depress
)
SELECT
    icd.ICD10SID,
    icd.ICD10Code,
    MAX(CASE WHEN crit.Comorbidity = 'Congestive heart failure' THEN 1 ELSE 0 END) AS CHF,
    MAX(CASE WHEN crit.Comorbidity = 'Cardiac arrhythmia' THEN 1 ELSE 0 END) AS Arrhy,
    MAX(CASE WHEN crit.Comorbidity = 'Valvular disease' THEN 1 ELSE 0 END) AS Valv,
    MAX(CASE WHEN crit.Comorbidity = 'Pulmonary circulation disorder' THEN 1 ELSE 0 END) AS PulmCirc,
    MAX(CASE WHEN crit.Comorbidity = 'Peripheral vascular disease' THEN 1 ELSE 0 END) AS Vasc,
    MAX(CASE 
        WHEN crit.Comorbidity = 'Hypertension, uncomplicated' THEN 1 
        WHEN crit.Comorbidity = 'Hypertension, complicated' THEN 1 
        ELSE 0
    END) AS HTN,
    MAX(CASE WHEN crit.Comorbidity = 'Paralysis' THEN 1 ELSE 0 END) AS Para,
    MAX(CASE WHEN crit.Comorbidity = 'Other neurological disorders' THEN 1 ELSE 0 END) AS Neuro,
    MAX(CASE WHEN crit.Comorbidity = 'Chronic pulmonary disease' THEN 1 ELSE 0 END) AS PulmChronic,
    MAX(CASE WHEN crit.Comorbidity = 'Diabetes, uncomplicated' THEN 1 ELSE 0 END) AS DiabUnc,
    MAX(CASE WHEN crit.Comorbidity = 'Diabetes, complicated' THEN 1 ELSE 0 END) AS DiabC,
    MAX(CASE WHEN crit.Comorbidity = 'Hypothyroidism' THEN 1 ELSE 0 END) AS Hypothy,
    MAX(CASE WHEN crit.Comorbidity = 'Renal failure' THEN 1 ELSE 0 END) AS RenFail,
    MAX(CASE WHEN crit.Comorbidity = 'Liver disease' THEN 1 ELSE 0 END) AS Liver,
    MAX(CASE WHEN crit.Comorbidity = 'Peptic ulcer disease excluding bleeding' THEN 1 ELSE 0 END) AS Peptic,
    MAX(CASE WHEN crit.Comorbidity = 'AIDS/HIV' THEN 1 ELSE 0 END) AS AIDS,
    MAX(CASE WHEN crit.Comorbidity = 'Lymphoma' THEN 1 ELSE 0 END) AS Lymphoma,
    MAX(CASE WHEN crit.Comorbidity = 'Metastatic cancer' THEN 1 ELSE 0 END) AS MetCancer,
    MAX(CASE WHEN crit.Comorbidity = 'Solid tumor without metastasis' THEN 1 ELSE 0 END) AS Tumor,
    MAX(CASE WHEN crit.Comorbidity = 'Rheumatoid arthritis/collagen vascular diseases' THEN 1 ELSE 0 END) AS Rheum,
    MAX(CASE WHEN crit.Comorbidity = 'Coagulopathy' THEN 1 ELSE 0 END) AS Coag,
    MAX(CASE WHEN crit.Comorbidity = 'Obesity' THEN 1 ELSE 0 END) AS Obesity,
    MAX(CASE WHEN crit.Comorbidity = 'Weight loss' THEN 1 ELSE 0 END) AS WLoss,
    MAX(CASE WHEN crit.Comorbidity = 'Fluid and electrolyte disorders' THEN 1 ELSE 0 END) AS Fluid,
    MAX(CASE WHEN crit.Comorbidity = 'Blood-loss anemia' THEN 1 ELSE 0 END) AS Blood,
    MAX(CASE WHEN crit.Comorbidity = 'Deficiency anemia' THEN 1 ELSE 0 END) AS Deficiency,
    MAX(CASE WHEN crit.Comorbidity = 'Alcohol abuse' THEN 1 ELSE 0 END) AS Alcohol,
    MAX(CASE WHEN crit.Comorbidity = 'Drug abuse' THEN 1 ELSE 0 END) AS Drug,
    MAX(CASE WHEN crit.Comorbidity = 'Psychoses' THEN 1 ELSE 0 END) AS Psych,
    MAX(CASE WHEN crit.Comorbidity = 'Depression' THEN 1 ELSE 0 END) AS Depress
FROM 
    CDWWork.Dim.ICD10 icd
    INNER JOIN
    #ICD10ElixhauserCriteria crit
        ON
        icd.ICD10Code LIKE crit.ICD10Prefix
WHERE
    LEN(icd.ICD10Code) <= 10
GROUP BY
    icd.ICD10SID,
    icd.ICD10Code
;

